spring:
  application:
    name: project_management

  datasource:
    url: jdbc:mysql://localhost:3306/projecteams
    username: root
    password: rootMySQL1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
