spring:
  application:
    name: project_management

  datasource:
    url: jdbc:mysql://localhost:3306/project_teams
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
